name: CI

# Runs build and test on:
#   every push that has a change in a file not in the docs folder
#   every pull request with main branch as the base that has a change in a file not in the docs folder
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Check and build codebase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Yarn Cache Directory Path
        id: cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('./yarn.lock') }}

      - name: Installation ${{ matrix.node-version }}
        run: yarn --prefer-offline --frozen-lockfile --non-interactive

      - name: Check Code ${{ matrix.node-version }}
        run: yarn lint

      - name: Compile Code ${{ matrix.node-version }}
        run: yarn compile-ts

      - name: Test Code ${{ matrix.node-version }}
        run: yarn test
